### ISSUE TITLE
Uncaught SecurityError

### ISSUE THREAD

**Issue by androng** [coinbase/multisig-tool#2]
When I enter my information and click the button under step 2, this shows up in the console. I suspect it's because my vault passphrase has a space in it--perhaps this is not handled by the javascript? 

 Uncaught SecurityError: Failed to construct 'Worker': Script at 'file://localhost/Users/andrew/Desktop/multisig-tool-master/multisig/bip38.js' cannot be accessed from origin 'null'.multisig.js:49 Multisig.Bip38Workermultisig.js:298 Multisig.App.buildTransactionindex.html:83 (anonymous function)jquery-2.1.1.min.js:3 n.event.dispatchjquery-2.1.1.min.js:3 r.handle

**Comment by mihar** [comment]
Hi @androng, the issue you're describing is due to browser's security policies and not allowing to initiate a worker from a local file.

As I can see from your error, you're running it through the `file://` protocol.

Please view the readme here at the section [Running locally](https://github.com/coinbase/multisig-tool#running-locally) for instructions regarding this.
